### ISSUE TITLE
pass options to command

### ISSUE THREAD

**Issue by benmonro** [whoeverest/wsrun#21]
i'd like an option to pass flags on to the script.

i.e. something like this: `wsrun build --watch` or something like that

**Comment by rotous** [comment]
I agree that this is a must-have.

**Comment by mnasyrov** [comment]
I managed to find out a workaround by passing a string with a command plus arguments to `wsrun`.
Here is an example where a new version is set to packages of yarn's workspaces (package.json):
```json
{
  "workspaces": ["packages/*"],
  "devDependencies": {
    "wsrun": "2.2.1"
  },
  "scripts": {
    "version": "yarn wsrun \"exec yarn version -- --new-version ${npm_package_version}\""
  }
}
```

**Comment by tommedema** [comment]
I had to go back to using Lerna because of this. Also, wsrun forces you to put its command line arguments after the command, which further complicates passing in extra args.

**Comment by spion** [comment]
Since 3.1 wsrun did a backward-incompatible change where the packages (if needed) are specified with `-p`, allowing you to pass additional arguments to the command.

Due to the awkward behavior of command argument separators, currently you need to use:

`yarn wsrun -- -- build --watch --other arguments here`

The first separator is interpreted by `yarn` and the other is interpreted by wsrun - you may put wsrun options inbetween, e.g.

`yarn wsrun -- --stages -r -- build --buildArg arg`

We'll try to remove the need to use `--` if we find an arguments parser that stops parsing after the first positional argument.
